---
- name: user
  hosts: pcs
  tasks:
    - name: Ajout d'un user toto
      user:
        name: toto
        password: "{{ 'tprli' | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
        state: present
        shell: /bin/bash