---
- name: package_web
  hosts: server
  tasks:
    - name: Ajout de git
      apt:
        name:
          - git
        state: present
    - name: Remove file (delete file)
      file:
        path: /var/www/html
        state: absent
    - name: clone du dépot
      git:
        clone: yes
        dest: /var/www/html
        repo: "https://github.com/splitbrain/dokuwiki.git"

  
